# Generated by Django 5.2.6 on 2025-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Electrical Installation', 'Electrical Installation'), ('Air Conditioning', 'Air Conditioning'), ('Maintenance & Repairs', 'Maintenance & Repairs'), ('Switchboard Upgrades', 'Switchboard Upgrades'), ('Lighting & Powerpoints', 'Lighting & Powerpoints'), ('Smoke Alarm Installation', 'Smoke Alarm Installation'), ('Safety Inspections', 'Safety Inspections'), ('Other Electrical Service', 'Other Electrical Service')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
            },
        ),
    ]
